kind: pipeline
type: docker
name: Deploy TripBot

steps:
  - name: Rebuild TripBot
    image: docker
    commands:
      - apk update
      - apk upgrade
      - apk add --no-cache git
      - docker compose -f docker-compose.host.yml --project-name tripsit-live up tripbot -d --force-recreate --build
      # - tail -f /dev/null
    environment:
      DOCKER_HOST:
        from_secret: DOCKER_HOST
      DOCKER_BUILDKIT:
        from_secret: DOCKER_BUILDKIT
      DISCORD_CLIENT_ID:
        from_secret: DISCORD_CLIENT_ID
      DISCORD_CLIENT_TOKEN:
        from_secret: DISCORD_CLIENT_TOKEN
      DISCORD_GUILD_ID:
        from_secret: DISCORD_GUILD_ID
      DISCORD_OWNER_ID:
        from_secret: DISCORD_OWNER_ID

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 1123644407434973255
      webhook_token:
        from_secret: WEBHOOK_TOKEN
      avatar_url: https://i.imgur.com/tnw3I34.png
      username: 'Drone CI'
      message: |
        {{#success build.status}}
        Build {{build.number}} succeeded.
        {{else}}
        Build {{build.number}} failed.
        {{/success}}
        Build time: {{build.started}}
        Commit message: {{commit.message}}
        Commit author: {{commit.author}}
        Commit branch: {{commit.branch}}
        {{#success build.status}}
        View logs: <{{build.link}}>
        {{else}}
        View failed job: <{{build.link}}>
        {{/success}}

trigger:
  branch:
  - Docker-update
trigger:
  event:
  # - cron
  - custom
  - push
  # - pull_request
  # - tag
  # - promote
  # - rollback