name: PullRequestOpen

on:
  pull_request:
    branches:
      - main
      - uat
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**/archive/**"
      - "**/legacy/**"
      - "**/matrix/**"
      - "**/telegram/**"
      - "**/irc/**"
      - "**/jest/**"
      - "**/build/**"
      - "**/@prisma-moodle/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Update npm
        run: npm install -g npm && npm --version
      - name: Install eslint
        run: npm install eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-airbnb-base eslint-config-airbnb-typescript eslint-config-google eslint-import-resolver-typescript eslint-plugin-import eslint-plugin-jest eslint-plugin-sonarjs --save-dev --legacy-peer-deps && npx eslint --version
      - name: Linting
        run: npx eslint --ext .ts,.js .
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Generate Prisma clients
        run: npm run db:generate
      - name: Type check
        run: npx tsc --noEmit
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Generate Prisma clients
        run: npm run db:generate
      - name: Copy env
        run: cp .env.example .env
      - name: Test
        run: npx jest --silent -c ./src/jest/jest.config.ts
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Generate Prisma clients
        run: npm run db:generate
      - name: Type check
        run: npx tsc --noEmit
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Generate Prisma clients
        run: npm run db:generate
      - name: Copy env
        run: cp .env.example .env
      - name: Test
        run: npx jest --silent -c ./src/jest/jest.config.ts
