# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Scan

on:
  push:
    branches:
      - dev/workflows
  push:
    branches:
      - main

jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '16.17.1'
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
    - name: Update npm
      run: npm install -g npm && npm --version
    - name: Install dependencies
      run: npm ci
    - name: Run scan
      run: npm run sonar-scanner



