name: Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '16.17.1'
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
    - name: Update npm
      run: npm install -g npm && npm --version
    - name: Install dependencies
      run: npm ci
    - name: Copy env
      run: cp .env.example .env
    - name: Test
      run: npm test

